### ISSUE TITLE
confusing name driver - is there a reason to keep gvnic as driver name and gve as module name

### ISSUE THREAD

**Issue by Ananth-vr** [GoogleCloudPlatform/compute-virtual-ethernet-linux#31]
Working on building a custom Linux image with gve/gvnic (not sure what to call the driver name or the module name) and noticed that our build scripts are failing as it checks for module name and then /sys/bus*

```
lspci -v |grep gv
        Kernel driver in use: gvnic
        Kernel modules: gve
```

 and then

`       ls /sys/bus/pci/drivers/gve/bind `

but it fails as  its `gvnic `instead of gve 
`

`Kernel: 5.4.144`

The same logic works with other network drivers we use on cloud i40e,ixgbe,ena etc 

```
lspci -v|grep ena
        Kernel driver in use: ena
        Kernel modules: ena
```
        
        
`ls /sys/bus/pci/drivers/ena/bind`

we have changed the build scripts but it would be nice to have an expected naming format like some of the other nic drivers used on Cloud.

**Comment by jfraker** [comment]
Thanks for the report!

This should be fixed as of v1.4.0
```
 lspci -v |grep gv
	Kernel driver in use: gve
	Kernel modules: gve
```
