### ISSUE TITLE
gVNIC driver module fails to compile on rhel8.8

### ISSUE THREAD

**Issue by chenamanda** [GoogleCloudPlatform/compute-virtual-ethernet-linux#41]
Hello, my GCP customer is getting compilations errors with the gVNIC driver module.  It looks like a patch is failing to apply due to the kernel version (4.18).  Details in attached file.  Any recommendations on how to proceed?

[gvnic_compile_errors.txt](https://github.com/GoogleCloudPlatform/compute-virtual-ethernet-linux/files/12314208/gvnic_compile_errors.txt)

**Comment by jeroendeb** [comment]
Fixed in 1.4.1.
