### ISSUE TITLE
Is the launch stage still early access

### ISSUE THREAD

**Issue by nique905** [GoogleCloudPlatform/compute-virtual-ethernet-linux#42]
On the readme we have

> This driver as well as the GCE VM virtual device are in Early Access stage [1], the feature is available to a closed group of testers.
>
> [1] https://cloud.google.com/terms/launch-stages

Wondering if we need to update this?

**Comment by jfraker** [comment]
Hi Shawnique, i've updated the README in the latest release to remove the early access note.
