### ISSUE TITLE
Release tarball not "multi-kernel compatible"

### ISSUE THREAD

**Issue by danielnorberg** [GoogleCloudPlatform/compute-virtual-ethernet-linux#48]
The readme mentions that: 

> If you downloaded a release tarball from GitHub: This source code should already be multi-kernel compatible. You can skip down to Compiling the Driver.

But the [v1.3.4](https://github.com/GoogleCloudPlatform/compute-virtual-ethernet-linux/releases/tag/v1.3.4) release tarball does not seem to be ready to compile as-is:

```
$ make -C /lib/modules/`uname -r`/build M=$(pwd)/build modules
make: Entering directory '/usr/src/kernels/5.15.0-202.135.2.el9uek.x86_64'
scripts/Makefile.build:44: /home/dano/compute-virtual-ethernet-linux-1.3.4/build/Makefile: No such file or directory
make[1]: *** No rule to make target '/home/dano/compute-virtual-ethernet-linux-1.3.4/build/Makefile'.  Stop.
make: *** [Makefile:1988: /home/dano/compute-virtual-ethernet-linux-1.3.4/build] Error 2
make: Leaving directory '/usr/src/kernels/5.15.0-202.135.2.el9uek.x86_64'
```

The above command succeeds if I follow the [Building the multi-kernel compatible driver source](https://github.com/GoogleCloudPlatform/compute-virtual-ethernet-linux?tab=readme-ov-file#building-the-multi-kernel-compatible-driver-source) instructions and use coccinelle to build the source, but on some distros installing coccinelle seems non-trivial and it would be helpful if the release tarballs would be ready to compile without coccinelle.

**Comment by jeroendeb** [comment]
1.4.1 contains the release tarball.
