### ISSUE TITLE
Support for ethtool --set-rxfh-indir to set the RSS hash key and indirection table

### ISSUE THREAD

**Issue by charredlot** [GoogleCloudPlatform/compute-virtual-ethernet-linux#55]
It's often useful to set the RSS hash key and indirection table for network applications, would it be possible to add the ethtool API corresponding to `--set-rxfh-indir` (i.e. `set_rxfh`/`get_rxfh` in the kernel `ethtool_ops`)? It seems from the comment here https://github.com/GoogleCloudPlatform/compute-virtual-ethernet-linux/blob/f2385de65e6f7f5d21f6b8e0cc1e3eae9e502e78/build/gve_desc.h#L90 that it's using the typical Toeplitz hash, and it's common for NICs to support changing those parameters.

Thanks for your consideration!

**Comment by jfraker** [comment]
Hi,

Just to give an update on this, we are currently in the process of upstreaming a patch series with these features. Our standard release process involves mirroring code to github once it's been accepted upstream, during the following merge window. So this should be available in the github driver ~2 months from now if all goes smoothly.

I'll leave this issue open for now, and let you know when we release RSS.

**Comment by jfraker** [comment]
We ended up doing an accelerated release for an unrelated issue, this should be available now. Let me know if you run into any issues.
