### ISSUE TITLE
Early Access/Container Optimized OS?

### ISSUE THREAD

**Issue by sgammon** [GoogleCloudPlatform/compute-virtual-ethernet-linux#7]
I think this may be in Beta now? In any case, is there any news about when this might land in Container Optimized OS?

**Comment by sgammon** [comment]
and/or is the `-cos` release for Container Optimized OS? ;)

**Comment by sagishah** [comment]
This is indeed in Beta now and the list of currently supported platforms can be found here: https://cloud.google.com/compute/docs/instances/create-vm-with-gvnic#os-support

Support for Container Optimized OS is planned for GA.

**Comment by catSully012** [comment]
gve is available in the following cos kernels: cos-4.19, cos-5.4 and cos-5.10.
